name: Build and Deploy Java App to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Java
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'microsoft'

    # Step 3: Build the application
    - name: Build the application
      run: |
        # Build the application using Maven
        mvn clean package -DskipTests
        # List the target directory contents to verify
        ls -l target/

    # Step 4: Deploy to Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'bank-server'  # Replace with your Azure Web App name
        slot-name: 'Production'
        package: 'target/bank-server-1.0.0.jar'  # Path to the built JAR file
